"""mistake in field types

Revision ID: d75ec9bc09e5
Revises: cdfbdd8f718b
Create Date: 2019-06-26 16:22:12.791452

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd75ec9bc09e5'
down_revision = 'cdfbdd8f718b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    with op.batch_alter_table('user') as batch_op:
        batch_op.drop_column('about_me')
    
    #op.drop_column('user', 'about_me')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('about_me', sa.DATETIME(), nullable=True))
    # ### end Alembic commands ###
